### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vishwanath-AI**

### CODE REVIEW

**Comment by 0x5eba** [comment]
Why do you want to remove the picture?

**Comment by vishwanath-AI** [comment]
It's an unexpected error I'm sorry !! 


May 5, 2020, 18:29 by notifications@github.com:

**Comment by 0x5eba** [comment]
No problem, star the project if you like it!

**Comment by vishwanath-AI** [comment]
Hey I found some one who is interested in this project but they are willing to buy it source code. 
5 May 2020, 18:29 by notifications@github.com:

**Comment by 0x5eba** [comment]
Give them my email me@sebastienbiollo.com or they can contact me here sebastienbiollo.com

**Comment by vishwanath-AI** [comment]
okay great I'll !! 


Jun 4, 2020, 01:39 by notifications@github.com:

**Pull request closed without merging**
